name: Check if you can Publish to JSR

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read
  id-token: write
jobs:
  jsr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Get tag version
        id: tag_version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if [[ $TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "version_ok=true" >> $GITHUB_OUTPUT
            echo "version=${TAG:1}" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - name: Dry run test
        if: steps.tag_version.outputs.version_ok == 'true'
        run: npx jsr publish --dry-run --set-version ${{ steps.tag_version.outputs.version }}
