name: Publish to JSR

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

jobs:
  jsr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} # Use the tag that triggered the event

      - name: Get tag version
        id: tag_version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if [[ $TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "version_ok=true" >> $GITHUB_OUTPUT
            echo "version=${TAG:1}" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - name: Publish to JSR
        if: steps.tag_version.outputs.version_ok == 'true'
        run: npx jsr publish --set-version ${{ steps.tag_version.outputs.version }}
